namespace Banking.NET.Commerzbank.CorporatePayments;

/// <summary>The direction of an <see cref="OrderType"/>.</summary>
public enum OrderDirection
{
    /// <summary>The order type is not one of the known Corporate Payments order types.</summary>
    Unknown = 0,

    /// <summary>The order type downloads a message generated by the bank.</summary>
    Download = 1,

    /// <summary>The order type uploads an order submitted by the customer.</summary>
    Upload = 2,
}
