<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(ToolsTargetFramework)</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>Banking.NET.Samples.Console</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Banking.NET\Banking.NET.csproj" />
  </ItemGroup>

</Project>
